# Generated by Django 4.2.11 on 2024-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_docente_acceso_recursos_ingles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='actividades_ingles_fuera_aula',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='docente',
            name='niveles_impartidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipo_senalizaciones_ingles',
            field=models.CharField(default='', max_length=100),
        ),
    ]
